{% set name = "deprecat" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deprecat-{{ version }}.tar.gz
  sha256: d93cdd493af68981f0c7d198c2b9df2358ead5e54ce3e671a3522af8785917e8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - wrapt >=1.10,<2

test:
  imports:
    - deprecat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deprecat/deprecat
  summary: Python @deprecat decorator to deprecate old python classes, functions or methods.
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - ocefpaf
